-- phpMyAdmin SQL Dump
-- version 4.6.6
-- https://www.phpmyadmin.net/
--
-- Anamakine: localhost
-- Üretim Zamanı: 05 May 2019, 12:17:34
-- Sunucu sürümü: 5.7.17-log
-- PHP Sürümü: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `maliyye`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `iqtisaditesnifat_paragraf`
--

CREATE TABLE `iqtisaditesnifat_paragraf` (
  `iqtisaditesnifat_paragraf_id` int(11) NOT NULL,
  `iqtisaditesnifat_kb_id` int(11) NOT NULL,
  `iqtisaditesnifat_paragraf_ad` varchar(250) COLLATE utf8_turkish_ci NOT NULL,
  `iqtisaditesnifat_paragraf_kod` int(11) NOT NULL,
  `iqtisaditesnifat_paragraf_status` enum('0','1') COLLATE utf8_turkish_ci NOT NULL DEFAULT '0',
  `iqtisaditesnifat_paragraf_aciqlama` text COLLATE utf8_turkish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

--
-- Tablo döküm verisi `iqtisaditesnifat_paragraf`
--

INSERT INTO `iqtisaditesnifat_paragraf` (`iqtisaditesnifat_paragraf_id`, `iqtisaditesnifat_kb_id`, `iqtisaditesnifat_paragraf_ad`, `iqtisaditesnifat_paragraf_kod`, `iqtisaditesnifat_paragraf_status`, `iqtisaditesnifat_paragraf_aciqlama`) VALUES
(11, 21, 'Ştatda olan işçilərin əməkhaqqı', 211100, '1', '<p><strong>211100. &ldquo;Ştatda olan iş&ccedil;ilərin əməkhaqqı&rdquo;</strong>&nbsp;paraqrafına ştatda olan iş&ccedil;ilərin və qulluq&ccedil;uların pul formasında aldıqları vəzifə (tarif) maaşı, vəzifə maaşına əlavələr, məzuniyyətə g&ouml;rə kompensasiya (istifadə edilməmiş məzuniyyətə g&ouml;rə kompensasiya daxil olmaqla) və hərbi qulluq&ccedil;uların (x&uuml;susi r&uuml;tbəsi olan əməkdaşların) pul təminatı ilə bağlı xərclər daxildir.</p>'),
(12, 21, 'Ştatdankənar işçilərin əməkhaqqı', 211200, '1', '<p><strong>211200. &ldquo;Ştatdankənar iş&ccedil;ilərin əməkhaqqı&rdquo;</strong>&nbsp;paraqrafına təşkilatların daimi ştatında olmayan və m&uuml;lki-h&uuml;quqi m&uuml;qavilə əsasında işlərin yerinə yetirilməsi &uuml;&ccedil;&uuml;n cəlb olunan şəxslərə hesablanmış əməkhaqlarının &ouml;dənişi ilə bağlı xərclər daxildir.</p>'),
(13, 21, 'Əməyin ödənişi ilə bağlı digər pul ödənişləri', 211900, '1', '<p><strong>211900. &ldquo;Əməyin &ouml;dənişi ilə bağlı digər pul &ouml;dənişləri&rdquo;</strong>&nbsp;paraqrafına iş&ccedil;ilərə, hərbi qulluq&ccedil;ulara (x&uuml;susi r&uuml;tbəsi olan əməkdaşlara) verilən m&uuml;kafatlar, maddi yardımlar, d&ouml;vlət orqanlarında &ccedil;alışan iş&ccedil;ilərə verilən b&uuml;t&uuml;n n&ouml;v m&uuml;avinətlər <strong>(279100-c&uuml; k&ouml;mək&ccedil;i b&ouml;lməsində nəzərdə tutulanlar istisna olmaqla),</strong> hakimlərə səlahiyyətlərin yerinə yetirilməsi ilə bağlı vergilərdən azad olunan aylıq pul təminatı, diplomatik xidmət əməkdaşlarına vəzifəyə təyin olunduqları diplomatik n&uuml;mayəndəliklərdə birdəfəlik m&uuml;avinət, ilk dəfə hakim vəzifəsinə təyin olunan şəxslərə &ouml;dənilən birdəfəlik yardım, həm&ccedil;inin istirahət, bayram və &uuml;mumxalq h&uuml;zn g&uuml;n&uuml; işə &ccedil;ıxmağa, əlavə iş saatlarına g&ouml;rə verilən &ouml;dənişlərlə bağlı xərclər daxildir.</p>'),
(14, 22, 'Məcburi dövlət sosial sığorta haqları', 212100, '1', '<p><strong>212100. &ldquo;Məcburi d&ouml;vlət sosial sığorta haqları&rdquo;&nbsp;</strong>paraqrafına iş&ccedil;i və qulluq&ccedil;uların əməkhaqlarına hesablanan və D&ouml;vlət Sosial M&uuml;dafiə Fonduna k&ouml;&ccedil;&uuml;r&uuml;lən xərclər daxildir.</p>'),
(15, 22, 'İcbari dövlət sığortası', 212200, '1', '<p><strong>212200. &ldquo;İcbari d&ouml;vlət sığortası&rdquo;&nbsp;</strong>paraqrafına qanunvericiliyə uyğun olaraq istehsalatda bədbəxt hadisələr və peşə xəstəlikləri nəticəsində peşə əmək qabiliyyətinin itirilməsi hallarından icbari sığorta ilə bağlı xərclər daxil edilir.</p>'),
(16, 22, 'İcbari tibbi sığorta', 212300, '1', '<p><strong>212300. &ldquo;İcbari tibbi sığorta&rdquo;</strong>&nbsp;paraqrafına icbari tibbi sığorta ilə bağlı xərclər daxildir.</p>'),
(17, 22, 'İşsizlikdən sığorta', 212400, '1', '<p><strong>212400. &ldquo;İşsizlikdən sığorta&rdquo;</strong>&nbsp;paraqrafına işsizlikdən sığorta ilə bağlı xərclər daxildir.</p>'),
(18, 23, 'Dəftərxana və təsərrüfat xərcləri', 221100, '1', '<p><strong>221100. &ldquo;Dəftərxana və təsərr&uuml;fat xərcləri&rdquo;</strong>&nbsp;paraqrafına m&uuml;xtəlif n&ouml;v kağızların, o c&uuml;mlədən faks, fotosurət &uuml;&ccedil;&uuml;n kağızların, rəsmxət və idarədə istifadə edilən dəftərxana və təsərr&uuml;fat ləvazimatlarının, m&uuml;hasibat, statistik, karg&uuml;zarlıq blanklarının və m&uuml;xtəlif cədvəllərin, po&ccedil;t nişanlarının alınması, idarədə istifadə olunan b&uuml;t&uuml;n n&ouml;v mal və materialların, printerlər &uuml;&ccedil;&uuml;n tonerlərin, katriclərin alınması, Azərbaycan Respublikasının xaricdə olan səfirlik, konsulluq və başqa diplomatik n&uuml;mayəndəliklərinə&nbsp;aid olan&nbsp;bu kimi dəftərxana və təsərr&uuml;fat xərcləri, həm&ccedil;inin bu qəbildən digər&nbsp;xərclər daxildir.</p>'),
(19, 23, 'Mətbəə məhsulları üzrə xərclər', 221200, '1', '<p><strong>221200. &ldquo;Mətbəə məhsulları &uuml;zrə xərclər&rdquo;</strong>&nbsp;paraqrafına dəftərxana işlərinin təşkili &uuml;zrə b&uuml;t&uuml;n n&ouml;v forma, buklet, registrlər, m&uuml;hasibat, statistik, karg&uuml;zarlıq blanklarının və m&uuml;xtəlif cədvəllərin, qiymətli kağızların hazırlanması və &ccedil;apı, mətbəə və nəşr ilə əlaqədar, həm&ccedil;inin maarifləndirmə (təbliğat-təşviqat) və reklam xarakterli &ccedil;ap materiallarının (məhsullarının) hazırlanması və ya alınması xərcləri, mətbəə &uuml;&ccedil;&uuml;n sərfiyyat materialların (mətbəə avadanlıqları &uuml;&ccedil;&uuml;n katriclərin, tonerlərin və mətbəə &uuml;&ccedil;&uuml;n m&uuml;xtəlif n&ouml;v sərfiyyat materiallarının) alınması və bu qəbildən olan digər xərclər daxildir.</p>'),
(20, 23, 'Yanacaq və sürtkü materiallarının alınması', 221300, '1', '<p><strong>221300. &ldquo;Yanacaq və s&uuml;rtk&uuml; materiallarının alınması&rdquo;</strong>&nbsp;paraqrafına təşkilata məxsus olan və ya icarəyə g&ouml;t&uuml;r&uuml;lm&uuml;ş nəqliyyat vasitələri, istehsal və x&uuml;susi təyinatlı texnikalar, avadanlıq və qurğular, habelə digər əsas fondlarla əlaqədar yanacaq və s&uuml;rtk&uuml; materiallarının alınması &uuml;zrə xərclər daxildir.</p>'),
(22, 23, 'Dərman, sarğı ləvazimatlarının və materiallarının alınması', 221400, '1', '<p><strong>221400. &ldquo;Dərman, sarğı ləvazimatlarının və materiallarının alınması&rdquo;&nbsp;</strong>paraqrafına xəstəliklərin profilaktikası, diaqnostikası və m&uuml;alicəsi &uuml;&ccedil;&uuml;n istifadə edilən x&uuml;susi malların alınmasına (bakterioloji preparatların və sarğı materiallarının) və xidmətlərin g&ouml;stərilməsinə sərf olunan xərclər, həm&ccedil;inin dərmanların, mineral suların, zərdabların, vaksinlərin, vitaminlərin, qida əlavələrinin, dezinfeksiyaedici vasitələrin, laboratoriya tədqiqatları və m&uuml;ayinələr &uuml;&ccedil;&uuml;n lazım olan materialların alınması, rentgen &ccedil;əkilişi &uuml;&ccedil;&uuml;n lentlərin, m&uuml;ayinələrin aparılması &uuml;&ccedil;&uuml;n materialların alınması, &ouml;z laboratoriyası olmadığı halda digər m&uuml;əssisələrdə aparılan m&uuml;ayinələrə, k&ouml;&ccedil;&uuml;rmə qanın alınmasına, donorlarla bağlı b&uuml;t&uuml;n xərclər, stasionar və ambulator xəstələrin, imtiyazlı xəstələrin profilaktikası, diaqnostikası və m&uuml;alicəsi &uuml;&ccedil;&uuml;n istifadə edilən x&uuml;susi malların alınmasına (bakterioloji preparatların və sarğı materiallarının) və xidmətlərin g&ouml;stərilməsinə sərf olunan xərclər, oksigen balonlarının alınması xərcləri, təhsil m&uuml;əssisələrində ilkin tibbi yardım &uuml;&ccedil;&uuml;n dərman, sarğı ləvazimatlarının və materiallarının alınmasına sərf olunan xərclər və bu qəbildən olan digər xərclər daxildir.</p>'),
(23, 23, 'Yumşaq inventar, yataq ləvazimatları və xüsusi geyimlərin alınması', 221500, '1', '<p><strong>221500. &ldquo;Yumşaq inventar, yataq ləvazimatları və x&uuml;susi geyimlərin alınması&rdquo;</strong>&nbsp;paraqrafına b&uuml;t&uuml;n n&ouml;v paltarların və geyimlərin,&nbsp;yataq ləvazimatlarının, trikotaj mallarının (par&ccedil;aların), pərdə alınması, həm&ccedil;inin paltarların, ayaqqabıların, yataq ləvazimatlarının, x&uuml;susi geyimin və dəyişəyin təmiri və tikilməsi, həm&ccedil;inin geyim və əşya əmlakı əvəzinə verilən pul kompensasiyalarının,&nbsp;habelə nağd qaydada (pul şəklində) qismən verilən kompensasiyaların &ouml;dənilməsi ilə&nbsp;bağlı xərclər, hərbi qulluq&ccedil;uların (x&uuml;susi r&uuml;tbəsi olan əməkdaşların),&nbsp;təhsil, səhiyyə m&uuml;əssisələrində&nbsp;sanitariya-gigiyena ehtiyaclarının təchizatı ilə bağlı xərclər daxildir.</p>'),
(24, 23, 'Ərzaq məhsullarının alınması və təminatı', 221600, '1', '<p><strong>221600. &ldquo;Ərzaq məhsullarının alınması və təminatı&rdquo;</strong>&nbsp;paraqrafına ərzaq məhsullarının alınması və dəyərinin &ouml;dənilməsi, həm&ccedil;inin hərbi qulluq&ccedil;ulara (x&uuml;susi r&uuml;tbəlilərə r&uuml;tbəsi olan əməkdaşlara), d&ouml;vlətin tapşırığı ilə ağır şəraitdə işləyənlərə natural formada verilən x&uuml;susi ərzaq məhsullarının dəyəri, ərzaq payı və yemək xərci əvəzinə &ouml;dənilən pul təminatı (kompensasiya),&nbsp;şagirdlərin yolda və təcr&uuml;bə yerlərində olduqları m&uuml;ddətdə g&uuml;ndəlik yemək xərclərinin &ouml;dənilməsi və bu qəbildən olan digər xərclər daxildir.</p>'),
(25, 23, 'Digər malların alınması', 221900, '1', '<p><strong>221900. &ldquo;Digər malların alınması&rdquo;</strong>&nbsp;paraqrafına əsas fond (vəsait) hesab edilməyən sair aktivlərin, o c&uuml;mlədən sayğacların alınması və quraşdırılması, yanğıns&ouml;nd&uuml;rən balonların alınması, toxucu saplarının alınması, portretlərin alınması, qan preparatlarının keyfiyyətinin m&uuml;əyyən edilməsi &uuml;&ccedil;&uuml;n qank&ouml;&ccedil;&uuml;rmə məntəqələri tərəfindən heyvanların alınması, təhsil m&uuml;əssisələri və başqa təşkilatlar tərəfindən elmi tədqiqat işləri və təcr&uuml;bə ke&ccedil;irilməsi &uuml;&ccedil;&uuml;n heyvanların və mal-qaranın alınması, idman atları &uuml;&ccedil;&uuml;n yem tədar&uuml;k&uuml; və alınması, uşaq m&uuml;əssisələrində uşaqlarla məşğələlər &uuml;&ccedil;&uuml;n m&uuml;xtəlif ləvazimatların, məktəb və rəsmxət ləvazimatlarının, materialların, yağlı, sulu boya, rəngli ş&uuml;şə, kimyəvi mayelər, gil alınması, təhsil proqramlarının alınması, tədris m&uuml;əssisələri &uuml;&ccedil;&uuml;n sinif jurnallarının, əyani vəsaitlərin, blankların, diplomların, şəhadətnamələrin, tələbə biletlərinin, kitab&ccedil;alarının, doğum, &ouml;l&uuml;m şəhadətnamələrinin və digər sənədlərin alınması, a&ccedil;ıq kitabxana şəbəkəsinə, tədris m&uuml;əssisələrinə, məktəblərə, şagirdlərə pulsuz verilən dərsliklərin dəyərinin &ouml;dənilməsi, jurnal və nəşrlərin alınması, elm, təhsil, səhiyyə, mədəniyyət və digər m&uuml;əssisələr &uuml;&ccedil;&uuml;n d&ouml;vri mətbuatın alınması, kitabxanalar &uuml;&ccedil;&uuml;n kitabxana əşyalarının və u&ccedil;ot sənədlərinin alınması, iş&ccedil;ilərin maddi həvəsləndirmə və qulluğa xitam verilməsi ilə bağlı hədiyyələrin alınması, bina və tikililərin şəhadətnamələrinin alınması və pasportlaşdırılması,&nbsp;yeməkxana və mətbəx ləvazimatlarının,&nbsp;hidrometeoroloji m&uuml;şahidələrin aparılmasında teletayp lenti, şarpilot m&uuml;şahidələr &uuml;&ccedil;&uuml;n k&uuml;rələr, zondlar, kaustik soda, elementlər, reaktivlər və sair istifadə olunan materialların alınmasına aid olan xərclər, lisenziyalı bədii, sənədli, cizgi filmlərinin və m&uuml;xtəlif proqramların prokatı və alınması, səhnə vəsaitlərinin (dekorasiyalar, butaforlar, teatr geyimləri, pariklər və sair səhnə vəsaitlərinin) alınması və bu qəbildən olan digər xərclər, həm&ccedil;inin 221100 &ndash; 221600-c&uuml; paraqraflarında qeyd olunmayan digər alışlarla bağlı xərclər daxildir.</p>'),
(26, 24, 'Cari təmir', 222100, '1', '<p><strong>222100. &ldquo;Cari təmir&rdquo;&nbsp;</strong>paraqrafına tikili və avadanlıqların, habelə əsas fond hesab edilən digər uzunm&uuml;ddətli aktivlərin texniki və iqtisadi g&ouml;stəricilərinin m&uuml;əyyən edilmiş hədd daxilində saxlanılması &uuml;&ccedil;&uuml;n (onun ayrı-ayrı tez sıradan &ccedil;ıxan (tezk&ouml;hnələn) hissələrinin və detallarının dəyişdirilməsi, bərpası, rənglənməsi, sazlanması) həyata ke&ccedil;irilən cari təmir işləri &uuml;zrə sərf olunan vəsait daxildir. Həm&ccedil;inin, sahibsiz qalmış, m&uuml;sadirə edilmiş əmlakların təşkilatlara verilməzdən əvvəl cari təmiri, meliorasiya və su təsərr&uuml;fatı sistemində istismar tədbirləri &uuml;zrə g&ouml;r&uuml;lən torpaq işlərinə, &ccedil;aylarda tənzimlənmə, sahilbərkitmə işlərinə, mexanizmlərə və nasos stansiyalarına ehtiyat hissələrinin alınması, cari təmirlə bağlı mal-materialların alınması ilə bağlı xərclər daxildir. Bu paraqraf &ldquo;222110. Tikili və avadanlıqların cari təmir xərcləri&rdquo;, &ldquo;222120. Nəqliyyat vasitələrinin cari təmir xərcləri&rdquo; və &ldquo;222130. Sair torpaq, tikili və avadanlıqların cari təmir xərcləri&rdquo; maddələrindən ibarətdir.</p>'),
(27, 24, 'Kommunal xidmətlərin haqqının ödənilməsi', 222200, '1', '<p><strong>222200. &ldquo;Kommunal xidmətlərin haqqının &ouml;dənilməsi&rdquo;&nbsp;paraqrafına m&uuml;xtəlif n&ouml;v kommunal və kommunikasiya xidmətləri (isitmə, qızdırıcı, su, qaz, elektrik enerjisi, kanalizasiya, rabitə, po&ccedil;t xidmətləri, kommunikasiya xətlərinin &ccedil;əkilişi və s.) daxildir. Bu paraqrafa &ldquo;222210. Elektrik enerjisi haqqının &ouml;dənilməsi&rdquo;, &ldquo;222220. Qaz haqqının &ouml;dənilməsi&rdquo;, &ldquo;222230. Su haqqının &ouml;dənilməsi&rdquo;, &ldquo;222240. Kanalizasiya xidmətləri haqqının &ouml;dənilməsi&rdquo;, &ldquo;222250. İstilik enerjisi (yanacaq) haqqının &ouml;dənilməsi&rdquo; və &ldquo;222290. Digər kommunal xidmətlərin haqqının &ouml;dənilməsi&rdquo; maddələrinin xərcləri daxildir.</strong></p>'),
(28, 24, 'Rabitə xidmətləri haqqının ödənilməsi', 222300, '1', '<p><strong>222300. &ldquo;Rabitə xidmətləri haqqının &ouml;dənilməsi&rdquo;</strong>&nbsp;paraqrafına &ldquo;222310. Telefon danışıq haqlarının &ouml;dənilməsi&rdquo;, &ldquo;222320. Po&ccedil;t xidmətləri haqqının &ouml;dənilməsi&rdquo;, &ldquo;222330. İnternet xidməti haqqının &ouml;dənilməsi&rdquo; və &ldquo;222340. Proqram təminatlarına xidmət haqlarının &ouml;dənilməsi&rdquo; maddələrinin xərcləri daxildir.</p>'),
(29, 24, 'Əsas fondların və digər aktivlərin icarəsi, kirayəsi, saxlanılması və mühafizəsi xərcləri', 222400, '1', '<p><strong>222400. &ldquo;Əsas fondların və digər aktivlərin icarəsi, kirayəsi, saxlanılması və m&uuml;hafizəsi xərcləri&rdquo;</strong>&nbsp;paraqrafına &ldquo;222410. İcarə və muzdlu xidmətlər&rdquo;, &ldquo;222420. Kirayə haqqı&rdquo;, &ldquo;222430. M&uuml;hafizə xərcləri&rdquo; və &ldquo;222440. Əsas fondların və digər aktivlərin saxlanılması xərcləri&rdquo; maddələrinin xərcləri daxildir.</p>'),
(30, 24, 'Ezamiyyə xərcləri', 222500, '1', '<p><strong>222500. &ldquo;Ezamiyyə xərcləri&rdquo;</strong>&nbsp;paraqrafına ezamiyyətlər və xidməti səfərlər zamanı gediş, g&uuml;ndəlik, mehmanxana və mənzil xərcləri, iş&ccedil;ilərin hərəkəti zamanı g&uuml;ndəlik və gediş xərcləri, xidməti səfərlər, kurslara və təhsil m&uuml;əssisələrinə sessiyalara, m&uuml;şavirə və konfranslara, ali və orta ixtisas təhsil idarələrini bitirən gənc m&uuml;təxəssislərin işə g&ouml;ndərilməsi ilə bağlı g&uuml;ndəlik və yol xərcləri, Azərbaycan Respublikasının diplomatik n&uuml;mayəndəliklərinə və konsulluqlarına işə təyin olunan, bu orqanlarda fəaliyyətini başa &ccedil;atdırıb geri qayıdan əməkdaşın və onun ailə &uuml;zvlərinin, habelə diplomatik xidmət əməkdaşının illik məzuniyyətlə bağlı Azərbaycan Respublikasına eyni vaxtda gəlməsi və işlədiyi d&ouml;vlətə qayıtması &uuml;&ccedil;&uuml;n nəqliyyat &uuml;zrə xərclər daxildir. Bu paraqraf &ldquo;222510. &Ouml;lkədaxili ezamiyyətlər&rdquo; və &ldquo;222520. Xarici ezamiyyətlər&rdquo; maddələrindən ibarətdir.</p>'),
(31, 24, 'Nəqliyyat vasitələri, istehsal təyinatlı maşın, avadanlıq və qurğular üzrə xidmət haqlarının ödənilməsi', 222600, '1', '<p><strong>222600. &ldquo;Nəqliyyat vasitələri, istehsal təyinatlı maşın, avadanlıq və qurğular &uuml;zrə xidmət haqlarının &ouml;dənilməsi&rdquo;</strong>&nbsp;paraqrafına təşkilatın balansında, həm&ccedil;inin istifadəsində olan və ya icarəyə g&ouml;t&uuml;r&uuml;lm&uuml;ş nəqliyyat vasitələri, istehsal təyinatlı maşın, avadanlıq və qurğuların texniki baxışdan ke&ccedil;irilməsi, m&uuml;lki məsuliyyətinin icbari sığortası və bu qəbildən olan digər xərclər daxildir.</p>'),
(32, 24, 'Elmi tədqiqat xidmətləri, təcrübə və müayinələrin haqqının ödənilməsi', 222700, '1', '<p><strong>222700. &ldquo;Elmi tədqiqat xidmətləri, təcr&uuml;bə və m&uuml;ayinələrin haqqının &ouml;dənilməsi&rdquo;</strong>&nbsp;paraqrafına elmi tədqiqat işlərinin, təcr&uuml;bələrin, tədqiqatların, təcr&uuml;bi eksperimental işlərin, elmi m&uuml;əssisə və təşkilatlar &uuml;&ccedil;&uuml;n kənar təşkilatlar tərəfindən yerinə yetirilən xidmətlərin, həm&ccedil;inin statistik, metroloji, ekoloji və digər tədqiqatların, habelə elmi tədqiqat işləri, təcr&uuml;bələr, tədqiqatlarla bağlı m&uuml;ayinələrin ke&ccedil;irilməsi, elmi m&uuml;əssisə və təşkilatlar &uuml;&ccedil;&uuml;n kənar təşkilatlar tərəfindən yerinə yetirilən m&uuml;ayinə xidmətlərinin və bu qəbildən olan digər iş və xidmətlərin haqqının &ouml;dənilməsi ilə bağlı xərclər daxil edilir.</p>'),
(33, 24, 'Geoloji-kəşfiyyat və topoqrafiya-geodeziya xidmətləri haqqının ödənilməsi', 222800, '1', '<p>222800. &ldquo;Geoloji-kəşfiyyat və topoqrafiya-geodeziya xidmətləri haqqının &ouml;dənilməsi&rdquo;&nbsp;paraqrafına m&uuml;xtəlif ekspedisiyaların təşkili, geoloji-axtarış, geoloji-kəşfiyyat və topoqrafiya-geodeziya işlərinə &ccedil;əkilən xərclər daxildir.</p>'),
(34, 24, 'Digər iş və xidmətlərin haqqının ödənilməsi', 222900, '1', '<p><strong>222900. &ldquo;Digər iş və xidmətlərin haqqının &ouml;dənilməsi&rdquo;</strong>&nbsp;paraqrafı &ldquo;222910. Atributların, m&uuml;kafatlandırma nişanlarının hazırlanması, təltif və m&uuml;kafatlandırma ilə bağlı xərclər&rdquo;, &ldquo;222920. İstehlaky&ouml;nl&uuml; m&uuml;xtəlif xidmətlər&rdquo;, &ldquo;222930. Abadlaşdırma xidmətləri haqqının &ouml;dənilməsi&rdquo;, &ldquo;222940. Bank və plastik kartların xərcləri&rdquo;, &ldquo;222940. Əməyin m&uuml;hafizəsi xərcləri&rdquo; və &ldquo;222990. Sair xərclər&rdquo; maddələrindən ibarətdir.</p>'),
(35, 26, 'Təmsilçilik xərcləri', 224100, '1', '<p><strong>224100. &ldquo;Təmsil&ccedil;ilik xərcləri&rdquo;</strong>&nbsp;paraqrafı &ldquo;224110. Beynəlxalq səviyyəli tədbirlərin ke&ccedil;irilməsi&rdquo; və &ldquo;224120. Xarici &ouml;lkələrin n&uuml;mayəndə heyətlərinin və rəsmi şəxslərinin qəbulu, onlara xidmət g&ouml;stərilməsi&rdquo; maddələrindən ibarətdir.</p>'),
(36, 26, 'Təşviqat xərcləri', 224200, '1', '<p><strong>224200. &ldquo;Təşviqat xərcləri&rdquo;&nbsp;</strong>paraqrafı &ldquo;224210. İxracın və xarici investisiyaların təşviqi&rdquo; və &ldquo;224220. Azərbaycan Respublikasının xaricdəki diplomatik n&uuml;mayəndəlikləri və konsulluqlarının təşviqat fəaliyyəti &uuml;zrə xərclər&rdquo; maddələrindən ibarətdir.</p>'),
(37, 27, 'Maliyyə-kredit institutları və təşkilatları üzrə ödənişlər', 241100, '1', '<p><strong>241100. &ldquo;Maliyyə-kredit institutları və təşkilatları &uuml;zrə &ouml;dənişlər&rdquo;&nbsp;</strong>paraqrafına beynəlxalq maliyyə-kredit institutlarından və təşkilatlardan alınmış kreditlərə g&ouml;rə faizlərin &ouml;dənilməsi ilə bağlı xərclər daxildir.</p>'),
(38, 27, 'Xarici dövlətlərə ödənişlər', 241200, '1', '<p><strong>241200. &ldquo;Xarici d&ouml;vlətlərə &ouml;dənişlər&rdquo;&nbsp;</strong>paraqrafına xarici d&ouml;vlətlərdən alınmış kreditlərə g&ouml;rə faizlərin &ouml;dənilməsi ilə bağlı xərclər daxildir.</p>'),
(39, 28, 'Mərkəzi dövlət idarəetmə orqanları üzrə ödənişlər', 242100, '1', '<p><strong>242100. &ldquo;Mərkəzi d&ouml;vlət idarəetmə orqanları &uuml;zrə &ouml;dənişlər&rdquo;</strong>&nbsp;paraqrafına d&ouml;vlətdaxili uduşlu istiqraz vərəqələri &uuml;zrə faiz &ouml;dənişləri və digər xərclər daxildir.</p>'),
(40, 28, 'Digər idarəetmə orqanları üzrə ödənişlər', 242200, '1', '<p><strong>242200. &ldquo;Digər idarəetmə orqanları &uuml;zrə &ouml;dənişlər&rdquo;</strong>&nbsp;paraqrafına d&ouml;vlət idarəetmə sektorunun başqa təbəqələrindən alınmış borc vəsaitləri &uuml;zrə faiz &ouml;dənişləri, o c&uuml;mlədən bələdiyyə orqanlarına və yerli icra orqanlarına faiz &ouml;dənişləri, həm&ccedil;inin b&uuml;dcədənkənar d&ouml;vlət fondlarına &ouml;dənilən faizlər &uuml;zrə xərclər daxildir.</p>'),
(41, 29, 'Mərkəzi Bank üzrə ödənişlər', 243100, '1', '<p><strong>243100. &ldquo;Mərkəzi Bank &uuml;zrə &ouml;dənişlər&rdquo;</strong>&nbsp;paraqrafına buraxılmış qiymətli kağızlara g&ouml;rə Mərkəzi Banka faizlərin &ouml;dənilməsi ilə bağlı xərclər daxildir.</p>'),
(42, 29, 'Dövlət təşkilatları üzrə ödənişlər', 243200, '1', '<p><strong>243200. &ldquo;D&ouml;vlət təşkilatları &uuml;zrə &ouml;dənişlər&rdquo;&nbsp;</strong>paraqrafına d&ouml;vlət təşkilatlarından alınmış kreditlərə g&ouml;rə faizlərin &ouml;dənilməsi xərcləri daxildir.</p>'),
(43, 29, 'Publik hüquqi şəxslər üzrə ödənişlər', 243300, '1', '<p><strong>243300. &ldquo;Publik h&uuml;quqi şəxslər &uuml;zrə &ouml;dənişlər&rdquo;</strong>&nbsp;paraqrafına publik h&uuml;quqi şəxslərdən alınmış kreditlər &uuml;zrə faizlərin &ouml;dənilməsi xərcləri daxildir.</p>'),
(44, 29, 'Digər təşkilatlar üzrə ödənişlər', 243900, '1', '<p><strong>243900. &ldquo;Digər təşkilatlar &uuml;zrə &ouml;dənişlər&rdquo;</strong>&nbsp;paraqrafına digər&nbsp;təşkilatlardan alınmış kreditlərə g&ouml;rə faizlər və bu qəbildən olan &ouml;dənişlərlə, həm&ccedil;inin 243100-243300-c&uuml; paraqraflarında əhatə edilməyən digər təşkilatlardan alınmış kreditlərə g&ouml;rə faizlərin &ouml;dənilməsi ilə bağlı xərclər daxildir.</p>'),
(45, 32, 'Dövlət müəssisələrinə subsidiyalar', 253100, '1', '<p><strong>253100. &ldquo;D&ouml;vlət m&uuml;əssisələrinə subsidiyalar&rdquo;</strong>&nbsp;paraqrafına d&ouml;vlət b&uuml;dcəsindən d&ouml;vlət m&uuml;əssisələrinə əvəzsiz verilən maliyyə vəsaitinin məbləği, o c&uuml;mlədən həmin m&uuml;əssisələr tərəfindən xaricə və &ouml;lkə daxilində sənaye və kommersiya mallarının satışı və xidmətlərin g&ouml;stərilməsi ilə bağlı yaranmış zərərin &ouml;dənilməsi &uuml;zrə xərclər və bu qəbildən olan digər xərclər daxildir.</p>'),
(46, 32, 'Qeyri-dövlət müəssisələrinə subsidiyalar', 253200, '1', '<p><strong>253200. &ldquo;Qeyri-d&ouml;vlət m&uuml;əssisələrinə subsidiyalar&rdquo;</strong>&nbsp;paraqrafına &ouml;zəl m&uuml;əssisələrə əvəzsiz verilən maliyyə vəsaitinin məbləği, o c&uuml;mlədən həmin m&uuml;əssisələr tərəfindən xaricə və &ouml;lkə daxilində sənaye və kommersiya mallarının satışı və xidmətlərin g&ouml;stərilməsi ilə bağlı yaranmış zərərin &ouml;dənilməsi &uuml;zrə xərclər və bu qəbildən olan digər xərclər daxildir.</p>'),
(47, 33, 'Cari məqsədlər üçün verilən qrantlar və digər ödənişlər', 261100, '1', '<p><strong>261100. &ldquo;Cari məqsədlər &uuml;&ccedil;&uuml;n verilən qrantlar və digər &ouml;dənişlər&rdquo;&nbsp;</strong>paraqrafına rezidentlərə cari məqsədlər &uuml;&ccedil;&uuml;n birdəfəlik və ya m&uuml;ntəzəm olaraq əvəzsiz verilən maliyyə və natura formasında qrantlar və digər yardımlar &uuml;zrə xərclər daxildir.</p>'),
(48, 33, 'Əsaslı məqsədlər üçün verilən qrantlar və digər ödənişlər', 261200, '1', '<p><strong>261200. &ldquo;Əsaslı məqsədlər &uuml;&ccedil;&uuml;n verilən qrantlar və digər &ouml;dənişlər&rdquo;</strong>&nbsp;paraqrafına rezidentlərə əsaslı &ouml;dənişlər &uuml;&ccedil;&uuml;n birdəfəlik və ya m&uuml;ntəzəm olaraq əvəzsiz verilən maliyyə və natura formasında qrantlar və digər yardımlar &uuml;zrə xərclər daxildir.</p>'),
(49, 33, 'Dotasiya', 261300, '1', '<p><strong>261300. &ldquo;Dotasiya&rdquo;</strong>&nbsp;paraqrafına d&ouml;vlət b&uuml;dcəsindən Nax&ccedil;ıvan Muxtar Respublikasının b&uuml;dcəsinə və yerli b&uuml;dcələrə onların gəlir və xərclərini tənzimləmək məqsədi ilə əvəzsiz verilən maliyyə vəsaiti daxildir. Bu paraqraf &ldquo;261310. Nax&ccedil;ıvan Muxtar Respublikasının b&uuml;dcəsinə verilən dotasiya&rdquo; və &ldquo;261320. Yerli b&uuml;dcələrə verilən dotasiya&rdquo; maddələrindən ibarətdir.</p>'),
(50, 33, 'Subvensiya', 261400, '1', '<p><strong>261400. &ldquo;Subvensiya&rdquo;&nbsp;</strong>paraqrafına məqsədli maliyyələşmənin həyata ke&ccedil;irilməsi &uuml;&ccedil;&uuml;n d&ouml;vlət b&uuml;dcəsindən Nax&ccedil;ıvan Muxtar Respublikasının b&uuml;dcəsinə və yerli b&uuml;dcələrə verilən, lakin həmin məqsəd &uuml;&ccedil;&uuml;n və ya m&uuml;əyyən edilmiş m&uuml;ddətdə istifadə edilmədikdə, geri qaytarılan maliyyə vəsaiti daxildir. Bu paraqraf &ldquo;261410. Nax&ccedil;ıvan Muxtar Respublikasının b&uuml;dcəsinə verilən subvensiya&rdquo; və &ldquo;261420. Yerli b&uuml;dcələrə verilən subvensiya&rdquo; maddələrindən ibarətdir.</p>'),
(51, 34, 'Xarici dövlətlərə verilən qrantlar və digər ödənişlər', 262100, '1', '<p><strong>262100. &ldquo;Xarici d&ouml;vlətlərə verilən qrantlar və digər &ouml;dənişlər&rdquo;&nbsp;</strong>paraqrafına xarici d&ouml;vlətlərə əvəzsiz verilən qrantlar və digər &ouml;dənişlərlə bağlı xərclər daxildir.</p>'),
(52, 34, 'Beynəlxalq təşkilatlara verilən qrantlar və digər ödənişlər', 262200, '1', '<p><strong>262200. &ldquo;Beynəlxalq təşkilatlara verilən qrantlar və digər &ouml;dənişlər&rdquo;</strong>&nbsp;paraqrafına beynəlxalq təşkilatlara əvəzsiz verilən qrantlar və digər &ouml;dənişlərlə bağlı xərclər daxildir.</p>'),
(53, 34, 'Digər qeyri-rezidentlərə verilən qrantlar və digər ödənişlər', 262300, '1', '<p><strong>262300. &ldquo;Digər qeyri-rezidentlərə verilən qrantlar və digər &ouml;dənişlər&rdquo;</strong>&nbsp;paraqrafına digər qeyri-rezidentlərə əvəzsiz verilən qrantlar və digər &ouml;dənişlərlə bağlı xərclər daxildir.</p>'),
(54, 35, 'Əmək pensiyası', 271100, '1', '<p><strong>271100. &ldquo;Əmək pensiyası&rdquo;</strong>&nbsp;paraqrafına yaşa g&ouml;rə, əlilliyə g&ouml;rə, ailə baş&ccedil;ısını itirməyə g&ouml;rə əmək pensiyalarının verilməsi ilə bağlı xərclər daxildir. Bu paraqraf &ldquo;271110. Yaşa g&ouml;rə əmək pensiyası&rdquo;, &ldquo;271120. Əlilliyə g&ouml;rə əmək pensiyası&rdquo; və &ldquo;271130. Ailə baş&ccedil;ısını itirməyə g&ouml;rə əmək pensiyası&rdquo; maddələrindən ibarətdir.</p>'),
(55, 35, 'Müavinət', 271200, '1', '<p><strong>271200. &ldquo;M&uuml;avinət&rdquo;</strong>&nbsp;paraqrafına sosial sığorta proqramları &uuml;zrə &ouml;dənilən m&uuml;avinətlərlə bağlı xərclər daxildir. Bu paraqraf &ldquo;271210. 3 yaşınadək uşağa qulluğa g&ouml;rə m&uuml;avinət&rdquo;, &ldquo;271220. Əmək qabiliyyətini m&uuml;vəqqəti itirməyə g&ouml;rə m&uuml;avinət&rdquo;, &ldquo;271230. Uşağın doğulması ilə bağlı m&uuml;avinət&rdquo;, &ldquo;271240. Hamiləliyə və doğuşa g&ouml;rə m&uuml;avinət&rdquo;, &ldquo;271250. Əmək zədəsi və ya peşə xəstəliyi &uuml;zrə &ouml;dənişlər&rdquo;, &ldquo;271260. Dəfn &uuml;&ccedil;&uuml;n m&uuml;avinət&rdquo; və &ldquo;271290. Digər m&uuml;avinətlər&rdquo; maddələrindən ibarətdir.</p>'),
(56, 35, 'Digər sosial sığorta ödənişləri', 271900, '1', '<p><strong>271900. &ldquo;Digər sosial sığorta &ouml;dənişləri&rdquo;</strong>&nbsp;paraqrafına sığorta proqramları &uuml;zrə &ouml;dənilən digər &ouml;dənişlərlə bağlı xərclər daxildir. Bu paraqraf &ldquo;271910.&nbsp;Aktiv məşğulluq&nbsp;tədbirləri &uuml;zrə &ouml;dənişlər&rdquo; və &ldquo;271920. Əlilliklə bağlı &ouml;dənişlər&rdquo; maddələrindən ibarətdir.</p>'),
(57, 36, 'Ünvanlı dövlət sosial yardımı', 272100, '1', '<p><strong>272100. &ldquo;&Uuml;nvanlı d&ouml;vlət sosial yardımı&rdquo;&nbsp;</strong>paraqrafına gəlirləri qanunvericiliklə m&uuml;əyyən olunmuş həddən aşağı olan ailələrə verilən yardımla bağlı xərclər daxildir.</p>'),
(58, 36, 'Aztəminatlı ailələrə verilən uşaq müavinətləri', 272200, '1', '<p><strong>272200. &ldquo;Aztəminatlı ailələrə verilən uşaq m&uuml;avinətləri&rdquo;</strong>&nbsp;paraqrafına qanunvericiliklə m&uuml;əyyən olunmuş hallarda aztəminatlı ailələrə yardım g&ouml;stərilməsi ilə bağlı xərclər daxildir. Bu paraqraf &ldquo;272210. Şəhid olanların uşaqlarına m&uuml;avinətlər&rdquo;, &ldquo;272220. M&uuml;haribə və 20 yanvar hadisəsi zamanı əlil olan ailələrin uşaqlarına aylıq m&uuml;avinət&rdquo;, &ldquo;272230. &Ccedil;ernobıl qəzasının nəticələrinin aradan qaldırılması ilə bağlı m&uuml;avinət&rdquo;, &ldquo;272240. M&uuml;ddətli həqiqi hərbi xidmətdə olan ailələrin uşaqlarına m&uuml;avinət&rdquo;, &ldquo;272250. Bir yaşadək uşağı olan aztəminatlı ailələrə m&uuml;avinət&rdquo; və &ldquo;272290. Digər m&uuml;avinətlər&rdquo; maddələrindən ibarətdir.</p>'),
(59, 36, 'Dövlət sosial yardımı', 272300, '1', '<p><strong>272300. &ldquo;D&ouml;vlət sosial yardımı&rdquo;</strong>&nbsp;paraqrafına qanunvericilikdə nəzərdə tutulmuş sosial m&uuml;avinətlərin verilməsi ilə bağlı xərclər daxildir. Bu paraqraf &ldquo;272310. Yaşa g&ouml;rə m&uuml;avinət&rdquo;, &ldquo;272320. Əlilliyə g&ouml;rə m&uuml;avinət&rdquo;, &ldquo;272330. Sağlamlıq imkanları məhdud 16 yaşadək əlil uşaqlara m&uuml;avinət&rdquo;, &ldquo;272340. Ailə baş&ccedil;ısını itirməyə g&ouml;rə m&uuml;avinət&rdquo;, &ldquo;272350. Qəyyumluğa g&ouml;rə m&uuml;avinət&rdquo;, &ldquo;272360. M&uuml;alicə xərci&rdquo; və &ldquo;272390. Digər m&uuml;avinətlər&rdquo; maddələrdən ibarətdir.</p>'),
(60, 36, 'Kommunal güzəştlər', 272400, '1', '<p><strong>272400. &ldquo;Kommunal g&uuml;zəştlər&rdquo;</strong>&nbsp;paraqrafına kommunal, nəqliyyat və digər xidmətlərə g&ouml;rə g&uuml;zəştlərin əvəzinə verilən m&uuml;avinətlərlə bağlı xərclər daxildir. Bu paraqraf &ldquo;272410. Şəhid ailəsi &uuml;zvlərinə m&uuml;avinət&rdquo;, &ldquo;272420. M&uuml;haribə veteranlarına m&uuml;avinət&rdquo; və &ldquo;272490. Digər m&uuml;avinətlər&rdquo; maddələrdən ibarətdir.</p>'),
(61, 36, 'Təqaüdlər', 272500, '1', '<p><strong>272500. &ldquo;Təqa&uuml;dlər&rdquo;</strong>&nbsp;paraqrafına təqa&uuml;dlərlə bağlı xərclər daxildir. Bu paraqraf &ldquo;272510. Fəxri adlara g&ouml;rə təqa&uuml;d&rdquo;, &ldquo;272520. Milli Qəhrəman adını alanlara verilən təqa&uuml;d&rdquo;, &ldquo;272530. 20 yanvar şəhidlərinin ailələrinə verilən təqa&uuml;d&rdquo;, &ldquo;272540. Fərdi təqa&uuml;dlər&rdquo;, &ldquo;272550. Şəhid ailələrinə verilən təqa&uuml;dlər&rdquo;, &ldquo;272560. 20 yanvar hadisələri ilə əlaqədar əlil olmuş şəxslərə verilən təqa&uuml;d&rdquo;, &ldquo;272570. Tələbələrə verilən təqa&uuml;dlər&rdquo; və &ldquo;272590. Digər təqa&uuml;dlər&rdquo; maddələrindən ibarətdir.</p>'),
(62, 36, 'Məcburi köçkünlərə və məskunlaşmamış qaçqınlara ödənişlər', 272600, '1', '<p><strong>272600. &ldquo;Məcburi k&ouml;&ccedil;k&uuml;nlərə və məskunlaşmamış qa&ccedil;qınlara &ouml;dənişlər&rdquo;</strong>&nbsp;paraqrafına məcburi k&ouml;&ccedil;k&uuml;nlərə və məskunlaşmamış qa&ccedil;qınlara m&ouml;vcud qanunvericiliyə uyğun olaraq &ouml;dənişlərin verilməsi ilə bağlı xərclər daxildir. Bu paraqraf &ldquo;272610. Məcburi k&ouml;&ccedil;k&uuml;nlər və onlara bərabər tutulan şəxslərə &ouml;dənişlər&rdquo; və &ldquo;272690. Digər &ouml;dənişlər&rdquo;&nbsp;maddələrindən ibarətdir.</p>'),
(63, 36, 'Sosial yardım üzrə digər ödənişlər', 272900, '1', '<p><strong>272900. &ldquo;Sosial yardım &uuml;zrə digər &ouml;dənişlər&rdquo;</strong>&nbsp;paraqrafına qanunvericiliklə m&uuml;əyyən edilmiş sosial yardım xarakterli &ouml;dənişlərlə bağlı xərclər daxildir.&nbsp;Bu paraqraf &ldquo;272910. Xidmət g&ouml;stərənlərə &ouml;dənişlər&rdquo;, &ldquo;272920. Avtomobil n&ouml;vbəsində dayanan əlillərə kompensasiya&rdquo;, &ldquo;272930. X&uuml;susi təhsilə cəlb edilənlərə m&uuml;avinət&rdquo;, &ldquo;272940. İnsan alverindən zərər &ccedil;əkmişlərə m&uuml;avinət&rdquo; və &ldquo;272990. Digər &ouml;dənişlər&rdquo; maddələrindən ibarətdir.</p>'),
(64, 37, 'Dövlət qulluqçularına ödənişlər', 279100, '1', '<p><strong>279100. &ldquo;D&ouml;vlət qulluq&ccedil;ularına &ouml;dənişlər&rdquo;&nbsp;</strong>paraqrafına d&ouml;vlət qulluq&ccedil;ularına sosial m&uuml;avinət formasında &ouml;dənilən xərclər (pensiya yaşına &ccedil;atmasına g&ouml;rə k&ouml;n&uuml;ll&uuml; işdən &ccedil;ıxmış və d&ouml;vlət qulluğuna xidmət illərinin minimum həddinə malik olmayan d&ouml;vlət qulluq&ccedil;ularına &ouml;m&uuml;rl&uuml;k m&uuml;avinət, pensiya yaşına &ccedil;atmasına g&ouml;rə k&ouml;n&uuml;ll&uuml; işdən &ccedil;ıxdıqda, hesablanmış aylıq pensiyanın m&uuml;əyyən olunmuş məbləğində birdəfəlik haqq) daxildir.</p>'),
(65, 37, 'Natura formada olan müavinətlər', 279200, '1', '<p><strong>279200. &ldquo;Natural formada olan m&uuml;avinətlər&rdquo;&nbsp;</strong>paraqrafına natural formada alınan m&uuml;avinətlərlə bağlı xərclər daxildir.</p>'),
(66, 37, 'Kommunal və digər xidmətlərə görə təzminat (kompensasiya)', 279300, '1', '<p><strong>279300. &ldquo;Kommunal və digər xidmətlərə g&ouml;rə təzminat (kompensasiya)&rdquo;</strong>&nbsp;paraqrafına respublikanın kənd rayonlarında yerləşən &uuml;mumtəhsil məktəblərində və səhiyyə m&uuml;əssisələrində ali və orta ixtisas təhsil m&uuml;əssisələrinin pedaqoji və tibb ixtisaslarını bitirən gənc m&uuml;təxəssislərə kommunal və digər xidmətlərə g&ouml;rə &ouml;dənilən təzminat (kompensasiya) və bu qəbildən olan digər xərclər daxildir.</p>'),
(67, 37, 'Digər müavinətlər', 279900, '1', '<p><strong>279900. &ldquo;Digər m&uuml;avinətlər&rdquo;&nbsp;</strong>paraqrafına d&ouml;vlət tərəfindən &ouml;dənilən digər m&uuml;avinətlərin xərcləri və 279100-279300-c&uuml; paraqraflarda &ouml;z əksini tapmayan digər m&uuml;avinət və yardımlarla bağlı xərclər daxildir.</p>'),
(68, 38, 'Tikili və avadanlıqlar', 311100, '1', '<p><strong>311100. &ldquo;Tikili və avadanlıqlar&rdquo;</strong>&nbsp;paraqrafına yaşayış binaları, qeyri-yaşayış binaları, qurğular (tikintilər), &ouml;t&uuml;r&uuml;c&uuml; qurğular, maşın və avadanlıqlarla bağlı xərclər daxildir. Bu paraqraf &ldquo;311110. Yaşayış binaları&rdquo;, &ldquo;311120. Qeyri-yaşayış binaları&rdquo;, &ldquo;311130. Qurğular (tikintilər)&rdquo;, &ldquo;311140. &Ouml;t&uuml;r&uuml;c&uuml; qurğular&rdquo; və &ldquo;311150. Maşın və avadanlıqlar&rdquo; maddələrindən ibarətdir.</p>'),
(69, 38, 'Nəqliyyat vasitələri', 311200, '1', '<p><strong>311200. &ldquo;Nəqliyyat vasitələri&rdquo;&nbsp;</strong>paraqrafına b&uuml;t&uuml;n n&ouml;v nəqliyyat vasitələrinin alınması və istehsalı ilə bağlı xərclər daxildir. Bu paraqraf &ldquo;311210. Hava nəqliyyatı vasitələri&rdquo;, &ldquo;311220. Dəmir yolu nəqliyyatı vasitələri&rdquo;, &ldquo;311230. Su nəqliyyatı vasitələri&rdquo;, &ldquo;311240. Xidmət nəqliyyatı vasitələri&rdquo;, &ldquo;311250. İstehsalat nəqliyyatı vasitələri&rdquo;, &ldquo;311260. Avtomobil nəqliyyatı vasitələri&rdquo; və &ldquo;311270. İdman nəqliyyatı vasitələri&rdquo; maddələrindən ibarətdir.</p>'),
(70, 38, 'Sair torpaq, tikili və avadanlıqlar', 311900, '1', '<p><strong>311900. &ldquo;Sair torpaq, tikili və avadanlıqlar&rdquo;&nbsp;</strong>paraqrafına iş vaxtı fəaliyyətinin asan yerinə yetirilməsinə k&ouml;mək etmək &uuml;&ccedil;&uuml;n nəzərdə tutulan &uuml;mumi və texniki təyinatlı predmetlər (mebel dəstləri, masalar, kreslolar, k&uuml;rs&uuml;lər, dolablar, şkaflar, stellajlar, dəmir seyflər, partalar, daşınan sədlər, asılqanlar, qarderoblar, divanlar, yanmayan &ordm;kaflar və yeşiklər, inventar taraları, daşınan &ccedil;adırlar, &ccedil;arpayılar, kovralit &ouml;rt&uuml;k və xal&ccedil;alar, portyerlər, jal&uuml;zlər), əməyin m&uuml;hafizəsi &uuml;&ccedil;&uuml;n uyğunlaşdırılmış x&uuml;susi avadanlıqlar (hidropultlar, stenderlər, əl nərdivanları, maye və dənəvərlərin saxlanması &uuml;&ccedil;&uuml;n x&uuml;susiləşdirilmiş qablar),&nbsp;idman və digər x&uuml;susi hərbi təyinatlı inventarların&nbsp;və bu kimi digər təsərr&uuml;fat inventarlarının alınması, quraşdırılması və istehsalı ilə bağlı xərclər daxildir.</p>'),
(71, 39, 'Tikili və avadanlıqların əsaslı təmiri', 312100, '1', '<p><strong>312100. &ldquo;Tikili və avadanlıqların əsaslı təmiri&rdquo;&nbsp;</strong>paraqrafına yaşayış binaları, qeyri-yaşayış tikililəri, qurğular (tikintilər), &ouml;t&uuml;r&uuml;c&uuml; qurğular, maşın və avadanlıqların əsaslı təmiri və əsaslı təmir işləri ilə bağlı layihə-smeta sənədlərinin hazırlanması ilə bağlı xərclər daxildir. Bu paraqraf &ldquo;312110. Yaşayış binalarının əsaslı təmiri&rdquo;, &ldquo;312120. Qeyri-yaşayış binalarının əsaslı təmiri&rdquo;, &ldquo;312130. Qurğuların (tikintilərin) əsaslı təmiri&rdquo;, &ldquo;312140. &Ouml;t&uuml;r&uuml;c&uuml; qurğuların əsaslı təmiri&rdquo; və &ldquo;312150. Maşın və avadanlıqların əsaslı təmiri&rdquo; maddələrindən ibarətdir.</p>'),
(72, 39, 'Nəqliyyat vasitələrinin əsaslı təmiri', 312200, '1', '<p><strong>312200. &ldquo;Nəqliyyat vasitələrinin əsaslı təmiri&rdquo;</strong>&nbsp;paraqrafına&nbsp;b&uuml;t&uuml;n n&ouml;v nəqliyyat vasitələrinin əsaslı təmiri və əsaslı təmir işləri ilə bağlı layihə-smeta sənədlərinin hazırlanması &uuml;zrə xərclər daxildir.</p>'),
(73, 39, 'Sair torpaq, tikili və avadanlıqların əsaslı təmiri', 312900, '1', '<p><strong>312900. &ldquo;Sair torpaq, tikili və avadanlıqların əsaslı təmiri&rdquo;&nbsp;</strong>paraqrafına iş vaxtı fəaliyyətin asan yerinə yetirilməsinə k&ouml;mək etmək &uuml;&ccedil;&uuml;n nəzərdə tutulan &uuml;mumi və texniki təyinatlı predmetlər (mebel dəstləri, masalar, kreslolar, k&uuml;rs&uuml;lər, dolablar, şkaflar, stellajlar, dəmir seyflər, partalar, daşınan sədlər, asılqanlar, qarderoblar, divanlar, yanmayan şkaflar və yeşiklər, inventar taraları, daşınan &ccedil;adırlar, &ccedil;arpayılar, xal&ccedil;alar, portyerlər, jal&uuml;zlər), əməyin m&uuml;hafizəsi &uuml;&ccedil;&uuml;n uyğunlaşdırılmış x&uuml;susi avadanlıqlar (hidropultlar, stenderlər, əl nərdivanları, maye və dənəvər məhsulların saxlanılması &uuml;&ccedil;&uuml;n x&uuml;susiləşdirilmiş qablar),&nbsp;idman və digər x&uuml;susi hərbi təyinatlı inventarların&nbsp;və bu kimi digər təsərr&uuml;fat inventarlarının, habelə &ldquo;316000. Sair uzunm&uuml;ddətli qeyri-maliyyə aktivləri&rdquo; k&ouml;mək&ccedil;i b&ouml;lməsində nəzərdə tutulmuş uzunm&uuml;ddətli qeyri-maliyyə aktivlərinin əsaslı təmiri və əsaslı təmir işləri ilə bağlı layihə-smeta sənədlərinin hazırlanması &uuml;zrə xərclər daxildir.</p>'),
(74, 45, 'Torpaq', 318100, '1', '<p><strong>318100. &ldquo;Torpaq&rdquo;</strong>&nbsp;paraqrafına torpağın, meşələrin (onlarda yerləşən tikinti obyekti və qurğular istisna olmaqla) alınması ilə bağlı xərclər daxildir.</p>'),
(75, 45, 'Yeraltı aktivlər və digər təbii aktivlər', 318200, '1', '<p><strong>318200. &ldquo;Yeraltı aktivlər və digər təbii aktivlər&rdquo;&nbsp;</strong>paraqrafına yerin təkində olan faydalı qazıntıların və digər təbii aktivlərin alınması ilə bağlı xərclər daxildir.</p>'),
(76, 46, 'Valyuta və depozitlər', 321100, '1', '<p><strong>321100. &ldquo;Valyuta və depozitlər&rdquo;</strong>&nbsp;paraqrafına &ouml;lkə daxilində d&ouml;vlətə məxsus cari və tranzit hesablar &uuml;zrə əməliyyatlar, il ərzində valyutanın qiymətinin dəyişməsi, qoyulmuş depozitlərin faizinin dəyişməsi ilə bağlı əməliyyatlar daxildir.</p>'),
(77, 46, 'Səhmlər istisna olmaqla qiymətli kağızlar', 321200, '1', '<p><strong>321200. &ldquo;Səhmlər istisna olmaqla qiymətli kağızlar&rdquo;</strong>&nbsp;paraqrafına &ouml;lkə daxilində d&ouml;vlət tərəfindən alınan qısam&uuml;ddətli və uzunm&uuml;ddətli qiymətli kağızlar &uuml;zrə əməliyyatlar daxildir. Bu paraqraf &ldquo;321210. Qısam&uuml;ddətli&rdquo; və &ldquo;321220. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(78, 46, 'Ssudalar', 321300, '1', '<p><strong>321300. &ldquo;Ssudalar&rdquo;&nbsp;</strong>paraqrafında d&ouml;vlət tərəfindən verilən ssudalar &uuml;zrə əməliyyatlar əks etdirilir. Bu paraqraf &ldquo;321310. Qısam&uuml;ddətli&rdquo; və &ldquo;321320. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(79, 46, 'Səhm və digər kapital', 321400, '1', '<p><strong>321400. &ldquo;Səhm və digər kapital&rdquo;</strong>&nbsp;paraqrafına d&ouml;vlət tərəfindən &ouml;lkə daxilində səhm və digər kapitalın alınması ilə bağlı əməliyyatlar daxildir. Bu paraqraf &ldquo;321410. Qısam&uuml;ddətli&rdquo; və &ldquo;321420. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(80, 46, 'Törəmə maliyyə alətləri', 321500, '1', '<p><strong>321500. &ldquo;T&ouml;rəmə maliyyə alətləri&rdquo;</strong>&nbsp;paraqrafına d&uuml;nya bazarında xarici valyutaların məzənnəsinin faiz dərəcələrinin, qiymətli kağızların məzənnəsinin dəyişməsi zamanı olan risklərdən m&uuml;dafiəsi ilə bağlı əməliyyatlar daxildir.</p>'),
(81, 46, 'Digər maliyyə aktivləri', 321900, '1', '<p><strong>321900. &ldquo;Digər maliyyə aktivləri&rdquo;&nbsp;</strong>paraqrafına 321100-321500-c&uuml; paraqraflara daxil edilməyən &ouml;lkə daxilində digər maliyyə aktivləri &uuml;zrə əməliyyatlar daxildir.</p>'),
(82, 47, 'Valyuta və depozitlər', 322100, '1', '<p><strong>322100. &ldquo;Valyuta və depozitlər&rdquo;&nbsp;</strong>paraqrafına &ouml;lkə xaricində d&ouml;vlətə məxsus cari və tranzit hesablar &uuml;zrə əməliyyatlar, il ərzində valyutanın qiymətinin dəyişməsi, qoyulmuş depozitlərin faizinin dəyişməsi ilə bağlı əməliyyatlar daxildir. Bu paraqraf &ldquo;322110. Xəzinənin vahid hesabı&rdquo; və &ldquo;322120. Gəlirlər &uuml;zrə tranzit hesab&rdquo; maddələrindən ibarətdir.</p>'),
(83, 47, 'Səhmlər istisna olmaqla qiymətli kağızlar', 322200, '1', '<p><strong>322200. &ldquo;Səhmlər istisna olmaqla qiymətli kağızlar&rdquo;&nbsp;</strong>paraqrafına &ouml;lkə xaricində d&ouml;vlət tərəfindən alınan qısam&uuml;ddətli və uzunm&uuml;ddətli qiymətli kağızlar &uuml;zrə əməliyyatlar daxildir. Bu paraqraf &ldquo;322210. Qısam&uuml;ddətli&rdquo; və &ldquo;322220. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(84, 47, 'Ssudalar', 322300, '1', '<p><strong>322300. &ldquo;Ssudalar&rdquo;&nbsp;</strong>paraqrafında d&ouml;vlət tərəfindən verilən ssudalar &uuml;zrə əməliyyatlar əks etdirilir. Bu paraqraf &ldquo;322310. Qısam&uuml;ddətli&rdquo; və &ldquo;322320. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(85, 47, 'Səhm və digər kapital', 322400, '1', '<p><strong>322400. &ldquo;Səhm və digər kapital&rdquo;&nbsp;</strong>paraqrafına d&ouml;vlət tərəfindən &ouml;lkə daxilində səhm və digər kapitalın alınması ilə bağlı əməliyyatlar daxildir. Bu paraqraf &ldquo;322410. Qısam&uuml;ddətli&rdquo; və &ldquo;322420. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(86, 47, 'Törəmə maliyyə alətləri', 322500, '1', '<p><strong>322500. &ldquo;T&ouml;rəmə maliyyə alətləri&rdquo;</strong>&nbsp;paraqrafına d&uuml;nya bazarında xarici valyutaların məzənnəsinin faiz dərəcələrinin, qiymətli kağızların məzənnəsinin dəyişməsi zamanı olan risklərdən m&uuml;dafiəsi ilə bağlı əməliyyatlar daxildir.</p>'),
(87, 47, 'Digər maliyyə aktivləri', 322900, '1', '<p><strong>322900. &ldquo;Digər maliyyə aktivləri&rdquo;</strong>&nbsp;paraqrafına 322100-322500-c&uuml; paraqraflarına daxil edilməyən &ouml;lkə daxilində digər maliyyə aktivləri &uuml;zrə əməliyyatlar daxildir.</p>'),
(88, 49, 'Valyuta və depozitlər', 331100, '1', '<p><strong>331100. &ldquo;Valyuta və depozitlər&rdquo;&nbsp;</strong>paraqrafına &ouml;lkə daxilində d&ouml;vlətin &uuml;zərinə d&uuml;şən və &ouml;hdəlik yaradan depozit və valyuta hesabları &uuml;zrə əməliyyatlar daxildir.</p>'),
(89, 49, 'Səhmlər istisna olmaqla qiymətli kağızlar', 331200, '1', '<p><strong>331200. &ldquo;Səhmlər istisna olmaqla qiymətli kağızlar&rdquo;</strong>&nbsp;paraqrafına &ouml;lkə daxilində buraxılmış uzunm&uuml;ddətli və qısam&uuml;ddətli qiymətli kağızlar &uuml;zrə əməliyyatlar daxildir. Bu paraqraf &ldquo;331210. Qısam&uuml;ddətli&rdquo; və &ldquo;331220. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(90, 49, 'Ssudalar', 331300, '1', '<p><strong>331300. &ldquo;Ssudalar&rdquo;</strong>&nbsp;paraqrafında d&ouml;vlət tərəfindən alınan ssudalar &uuml;zrə əməliyyatlar əks etdirilir. Bu paraqraf &ldquo;331310. Qısam&uuml;ddətli&rdquo; və &ldquo;331320. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(91, 49, 'Səhm və digər kapital', 331400, '1', '<p><strong>331400. &ldquo;Səhm və digər kapital&rdquo;&nbsp;</strong>paraqrafına d&ouml;vlət tərəfindən &ouml;lkə daxilində səhm və digər kapitalın buraxılması ilə bağlı əməliyyatlar daxildir. Bu paraqraf &ldquo;331410. Qısam&uuml;ddətli&rdquo; və &ldquo;331420. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(92, 49, 'Digər maliyyə öhdəlikləri', 331500, '1', '<p><strong>331500. &ldquo;Digər maliyyə &ouml;hdəlikləri&rdquo;</strong>&nbsp;paraqrafına 331100-331400-c&uuml; paraqraflarına daxil edilməyən &ouml;lkə daxilində digər maliyyə &ouml;hdəlikləri &uuml;zrə əməliyyatlar daxildir.</p>'),
(93, 50, 'Valyuta və depozitlər', 332100, '1', '<p><strong>332100. &ldquo;Valyuta və depozitlər&rdquo;&nbsp;</strong>paraqrafına &ouml;lkə xaricində d&ouml;vlətin &uuml;zərinə d&uuml;şən və &ouml;hdəlik yaradan depozit və valyuta hesabları &uuml;zrə əməliyyatlar daxildir.</p>'),
(94, 50, 'Səhmlər istisna olmaqla qiymətli kağızlar', 332200, '1', '<p><strong>332200. &ldquo;Səhmlər istisna olmaqla qiymətli kağızlar&rdquo;</strong>&nbsp;paraqrafına &ouml;lkə xaricində alınmış uzunm&uuml;ddətli və qısam&uuml;ddətli qiymətli kağızlar &uuml;zrə əməliyyatlar daxildir. Bu paraqraf &ldquo;332210. Qısam&uuml;ddətli&rdquo; və &ldquo;332220. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(95, 50, 'Ssudalar', 332300, '1', '<p><strong>332300. &ldquo;Ssudalar&rdquo;&nbsp;</strong>paraqrafına d&ouml;vlət tərəfindən xaricdən alınan uzunm&uuml;ddətli və qısam&uuml;ddətli ssudalar &uuml;zrə əməliyyatlar daxildir. Bu paraqraf &ldquo;332310. Qısam&uuml;ddətli&rdquo; və &ldquo;332320. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(96, 50, 'Səhm və digər kapital', 332400, '1', '<p><strong>332400. &ldquo;Səhm və digər kapital&rdquo;</strong>&nbsp;paraqrafına d&ouml;vlət tərəfindən &ouml;lkə xaricində səhm və digər kapitalın buraxılması ilə bağlı əməliyyatlar daxildir. Bu paraqraf &ldquo;332410. Qısam&uuml;ddətli&rdquo; və &ldquo;332420. Uzunm&uuml;ddətli&rdquo; maddələrindən ibarətdir.</p>'),
(97, 50, 'Digər maliyyə öhdəlikləri', 332500, '1', '<p><strong>332500. &ldquo;Digər maliyyə &ouml;hdəlikləri&rdquo;</strong>&nbsp;paraqrafına digər maliyyə &ouml;hdəlikləri ilə bağlı əməliyyatlar daxildir.</p>');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `iqtisaditesnifat_paragraf`
--
ALTER TABLE `iqtisaditesnifat_paragraf`
  ADD PRIMARY KEY (`iqtisaditesnifat_paragraf_id`),
  ADD UNIQUE KEY `iqtisaditesnifat_paragraf_id` (`iqtisaditesnifat_paragraf_id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `iqtisaditesnifat_paragraf`
--
ALTER TABLE `iqtisaditesnifat_paragraf`
  MODIFY `iqtisaditesnifat_paragraf_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=98;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
