-- phpMyAdmin SQL Dump
-- version 4.6.6
-- https://www.phpmyadmin.net/
--
-- Anamakine: localhost
-- Üretim Zamanı: 05 May 2019, 12:17:25
-- Sunucu sürümü: 5.7.17-log
-- PHP Sürümü: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `maliyye`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `iqtisaditesnifat_kb`
--

CREATE TABLE `iqtisaditesnifat_kb` (
  `iqtisaditesnifat_kb_id` int(11) NOT NULL,
  `iqtisaditesnifat_bolme_id` int(11) NOT NULL,
  `iqtisaditesnifat_kb_ad` varchar(250) COLLATE utf8_turkish_ci NOT NULL,
  `iqtisaditesnifat_kb_kod` int(11) NOT NULL,
  `iqtisaditesnifat_kb_status` enum('0','1') COLLATE utf8_turkish_ci NOT NULL DEFAULT '0',
  `iqtisaditesnifat_kb_aciqlama` text COLLATE utf8_turkish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;

--
-- Tablo döküm verisi `iqtisaditesnifat_kb`
--

INSERT INTO `iqtisaditesnifat_kb` (`iqtisaditesnifat_kb_id`, `iqtisaditesnifat_bolme_id`, `iqtisaditesnifat_kb_ad`, `iqtisaditesnifat_kb_kod`, `iqtisaditesnifat_kb_status`, `iqtisaditesnifat_kb_aciqlama`) VALUES
(21, 32, 'Əməkhaqqı', 211000, '1', '<p><strong>211000</strong>. <strong>&ldquo;Əməkhaqqı&rdquo;&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinin xərclərinə &ldquo;211100</strong>. <strong>Ştatda olan iş&ccedil;ilərin əməkhaqqı&rdquo;, &rdquo;211200. Ştatdankənar iş&ccedil;ilərin əməkhaqqı&rdquo; və &ldquo;211900. Əməyin &ouml;dənişi ilə bağlı digər pul &ouml;dənişləri&rdquo;</strong> paraqraflarının xərcləri daxildir.</p>'),
(22, 32, 'Əmək- haqqına görə ayırmalar', 212000, '1', '<p><strong>212000. &ldquo;Əməkhaqqına ayırmalar&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə m&uuml;əyyənləşdirilmiş normativlərə əsasən işəg&ouml;t&uuml;rənlərin sosial m&uuml;dafiə ayırmaları &uuml;zrə xərclər daxil edilir. Bu k&ouml;mək&ccedil;i b&ouml;lməyə &ldquo;212100.&nbsp;Məcburi d&ouml;vlət sosial sığorta haqları&rdquo;, &ldquo;212200. İcbari d&ouml;vlət sığortası&rdquo;, &ldquo;212300. İcbari tibbi sığorta&rdquo; və &ldquo;212400. İşsizlikdən sığorta&rdquo; paraqraflarının xərcləri daxildir.</p>'),
(23, 33, 'Malların satınalınması', 221000, '1', '<p><strong>221000</strong>.<strong> &ldquo;Malların satınalınması&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə &ldquo;221100. Dəftərxana və təsərr&uuml;fat xərcləri&rdquo;, &ldquo;221200. Mətbəə məhsulları &uuml;zrə xərclər&rdquo;, &ldquo;221300.Yanacaq və s&uuml;rtk&uuml; materiallarının alınması&rdquo;, &ldquo;221400. Dərman, sarğı ləvazimatlarının və materiallarının alınması&rdquo;, &ldquo;221500. Yumşaq inventar, yataq ləvazimatlarının və x&uuml;susi geyimlərin alınması&rdquo;, &ldquo;221600. Ərzaq məhsullarının alınması və təminatı&rdquo; və &ldquo;221900. Digər malların alınması&rdquo; paraqraflarının xərcləri daxildir.</p>'),
(24, 33, 'İş və xidmətlərin alınması', 222000, '1', '<p><strong>222000. &ldquo;İş və xidmətlərin alınması&rdquo;&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə &ldquo;222100. Cari təmir&rdquo;, &ldquo;222200. Kommunal xidmətlərin haqqının &ouml;dənilməsi&rdquo;, &ldquo;222300. Rabitə xidmətləri haqqının &ouml;dənilməsi&rdquo;, &ldquo;222400. Əsas fondların və digər aktivlərin icarəsi, kirayəsi, saxlanılması və m&uuml;hafizəsi xərcləri&rdquo;, &ldquo;222500. Ezamiyyə xərcləri&rdquo;, &ldquo;222600. Nəqliyyat vasitələri, istehsal təyinatlı maşın, avadanlıq və qurğular &uuml;zrə xidmət haqlarının &ouml;dənilməsi&rdquo;, &ldquo;222700. Elmi tədqiqat xidmətləri, təcr&uuml;bə və m&uuml;ayinələrin haqqının &ouml;dənilməsi&rdquo;, &ldquo;222800. Geoloji-kəşfiyyat və topoqrafiya-geodeziya xidmətləri haqqının &ouml;dənilməsi&rdquo; və &ldquo;222900. Digər iş və xidmətlərin haqqının &ouml;dənilməsi&rdquo; paraqraflarının xərcləri daxildir.</strong></p>'),
(25, 33, 'Beynəlxalq təşkilatlara üzvlüklə bağlı ödənişlər', 223000, '1', '<p><strong>223000. &ldquo;Beynəlxalq təşkilatlara &uuml;zvl&uuml;klə bağlı &ouml;dənişlər&rdquo;&nbsp;</strong>k&ouml;mək&ccedil;i b&ouml;lməsinə Azərbaycan Respublikasının &uuml;zv olduğu beynəlxalq və regional təşkilatlara, o c&uuml;mlədən beynəlxalq konvensiyalara g&ouml;t&uuml;r&uuml;lm&uuml;ş &ouml;hdəliklər &uuml;zrə m&uuml;ntəzəm olaraq &ouml;dənilən &uuml;zvl&uuml;k haqqı və ianə xərcləri daxildir.</p>'),
(26, 33, 'Təmsilçilik və təşviqat xərcləri', 224000, '1', '<p><strong>224000. &ldquo;Təmsil&ccedil;ilik və təşviqat xərcləri&rdquo;&nbsp;</strong>k&ouml;mək&ccedil;i b&ouml;lməsinə &ouml;lkə daxilində və xaricdə beynəlxalq səviyyəli tədbirlərin (forum, konfrans, seminar, simpozium, sərgi, yarmarka və s.) təşkili, xarici &ouml;lkələrin n&uuml;mayəndə heyətlərinin və rəsmi şəxslərinin qəbulu, onlara xidmət g&ouml;stərilməsi ilə bağlı xərclər daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;224100. Təmsil&ccedil;ilik xərcləri&rdquo; və &ldquo;224200. Təşviqat xərcləri&rdquo; paraqraflarından ibarətdir.</p>'),
(27, 35, 'Qeyri -rezidentlər üzrə ödənişlər', 241000, '1', '<p><strong>241000. &ldquo;Qeyri-rezidentlər &uuml;zrə &ouml;dənişlər&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə xarici təşkilatlara faizlər &uuml;zrə &ouml;dənişlər daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;241100. Maliyyə-kredit institutları və təşkilatları &uuml;zrə &ouml;dənişlər&rdquo; və &ldquo;241200. Xarici d&ouml;vlətlərə &ouml;dənişlər&rdquo; paraqraflarından ibarətdir.</p>'),
(28, 35, 'Dövlət idarəetmə sektoru üzrə ödənişlər', 242000, '1', '<p><strong>242000. &ldquo;D&ouml;vlət idarəetmə sektoru &uuml;zrə &ouml;dənişlər&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinin xərclərinə d&ouml;vlət idarəetmə orqanlarına və digər idarəetmə orqanlarına faizlərlə bağlı xərclər daxil edilir.&nbsp;Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;242100. Mərkəzi d&ouml;vlət idarəetmə orqanları &uuml;zrə &ouml;dənişlər&rdquo; və &ldquo;242200. Digər idarəetmə orqanları &uuml;zrə &ouml;dənişlər&rdquo; paraqraflarından ibarətdir.</p>'),
(29, 35, 'Dövlət idarəetmə sektoruna aid olmayan təşkilatlar üzrə ödənişlər', 243000, '1', '<p><strong>243000. &ldquo;D&ouml;vlət idarəetmə sektoruna aid olmayan təşkilatlar &uuml;zrə &ouml;dənişlər&rdquo;&nbsp;</strong>k&ouml;mək&ccedil;i b&ouml;lməsinə Mərkəzi Banka, d&ouml;vlət təşkilatlarına, &ouml;zəl təşkilatlara, bank olmayan kredit təşkilatlarına və publik h&uuml;quqi şəxslərə faizlər &uuml;zrə &ouml;dənişlər daxil edilir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;243100. Mərkəzi Bank &uuml;zrə &ouml;dənişlər&rdquo;, &ldquo;243200. D&ouml;vlət təşkilatları &uuml;zrə &ouml;dənişlər&rdquo;, &ldquo;243300. Publik h&uuml;quqi şəxslər &uuml;zrə &ouml;dənişlər&rdquo; və &ldquo;243900. Digər təşkilatlar &uuml;zrə &ouml;dənişlər&rdquo; paraqraflarından ibarətdir.</p>'),
(30, 36, 'Naxçıvan Muxtar Respublikasının büdcəsinə subsidiyalar', 251000, '1', '<p><strong>251000. &ldquo;Nax&ccedil;ıvan Muxtar Respublikasının b&uuml;dcəsinə subsidiyalar&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə d&ouml;vlət b&uuml;dcəsindən Nax&ccedil;ıvan Muxtar Respublikasının b&uuml;dcəsinə əvəzsiz verilən maliyyə vəsaitinin məbləği daxildir.</p>'),
(31, 36, 'Yerli büdcələrə subsidiyalar', 252000, '1', '<p><strong>252000. &ldquo;Yerli b&uuml;dcələrə subsidiyalar&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə d&ouml;vlət b&uuml;dcəsindən yerli b&uuml;dcələrə əvəzsiz verilən maliyyə vəsaitinin məbləği daxildir.</p>'),
(32, 36, 'Hüquqi şəxslərə subsidiyalar', 253000, '1', '<p><strong>253000. &ldquo;H&uuml;quqi şəxslərə subsidiyalar&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsi &ldquo;253100. D&ouml;vlət m&uuml;əssisələrinə subsidiyalar&rdquo; və &ldquo;253200. Qeyri-d&ouml;vlət m&uuml;əssisələrinə subsidiyalar&rdquo; paraqraflarından ibarətdir.</p>'),
(33, 37, 'Rezidentlərə verilən qrantlar və digər ödənişlər', 261000, '1', '<p><strong>261000. &ldquo;Rezidentlərə verilən qrantlar və digər &ouml;dənişlər&rdquo;&nbsp;</strong>k&ouml;mək&ccedil;i b&ouml;lməsinə rezidentlərə cari və əsaslı məqsədlər &uuml;&ccedil;&uuml;n əvəzsiz verilən qrantlar və digər &ouml;dənişlər daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;261100. Cari məqsədlər &uuml;&ccedil;&uuml;n verilən qrantlar və digər &ouml;dənişlər&rdquo;, &ldquo;261200. Əsaslı məqsədlər &uuml;&ccedil;&uuml;n verilən qrantlar və digər &ouml;dənişlər&rdquo;, &ldquo;261300. Dotasiya&rdquo; və &ldquo;261400. Subvensiya&rdquo; paraqraflarından ibarətdir.</p>'),
(34, 37, 'Qeyri-rezidentlərə verilən qrantlar və digər ödənişlər', 262000, '1', '<p><strong>262000. &ldquo;Qeyri-rezidentlərə verilən qrantlar və digər &ouml;dənişlər&rdquo;&nbsp;</strong>k&ouml;mək&ccedil;i b&ouml;lməsinə qeyri-rezidentlərə cari və əsaslı məqsədlər &uuml;&ccedil;&uuml;n əvəzsiz verilən qrantlar və digər &ouml;dənişlər daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;262100. Xarici d&ouml;vlətlərə verilən qrantlar və digər &ouml;dənişlər&rdquo;, &ldquo;262200. Beynəlxalq təşkilatlara verilən qrantlar və digər &ouml;dənişlər&rdquo; və &ldquo;262300. Digər qeyri-rezidentlərə verilən qrantlar və digər &ouml;dənişlər&rdquo; paraqraflarından ibarətdir.</p>'),
(35, 38, 'Sosial sığorta', 271000, '1', '<p><strong>271000. &ldquo;Sosial sığorta&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə &ouml;dənilən pensiyalar, m&uuml;avinətlər, yardımlar &uuml;zrə xərclər daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;271100. Əmək pensiyası&rdquo;, &ldquo;271200. M&uuml;avinət&rdquo; və &ldquo;271900. Digər sosial sığorta &ouml;dənişləri&rdquo; paraqraflarından ibarətdir.</p>'),
(36, 38, 'Sosial yardım', 272000, '1', '<p><strong>272000. &ldquo;Sosial yardım&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə m&ouml;vcud qanunvericiliyə uyğun olaraq nəzərdə tutulmuş aztəminatlı ailələrə, himayəsində uşağı olan aztəminatlı ailələrə, ailə baş&ccedil;ısını itirən aztəminatlı ailələrə &ouml;dənilən m&uuml;avinətlər, aztəminatlı ailələrə &uuml;nvanlı d&ouml;vlət sosial yardımının &ouml;dənilməsi, m&uuml;ddətli hərbi xidmətdə olanların uşaqlarına verilən aylıq m&uuml;avinət, m&uuml;haribə əlillərinin, 20 yanvar hadisələri zamanı əlil olanların uşaqlarına verilən aylıq m&uuml;avinət, &Ccedil;ernobıl qəzası nəticəsində I və II qrup əlil olmuş, yaxud vəfat etmiş valideynlərin uşaqlarına, habelə &Ccedil;ernobıl qəzası nəticələrinin aradan qaldırılması iştirak&ccedil;ılarının dispanser qeydiyyatında olan uşaqlarına, insan alverindən zərər &ccedil;əkmiş şəxslərə reinteqrasiya d&ouml;vr&uuml;ndə m&uuml;avinət &ouml;dənilməsi ilə bağlı xərclər daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;272100. &Uuml;nvanlı d&ouml;vlət sosial yardımı&rdquo;, &ldquo;272200. Aztəminatlı ailələrə verilən uşaq m&uuml;avinətləri&rdquo;, &ldquo;272300. D&ouml;vlət sosial yardımı&rdquo;, &ldquo;272400. Kommunal g&uuml;zəştlər&rdquo;, &ldquo;272500. Təqa&uuml;dlər&rdquo;, &ldquo;272600. Məcburi k&ouml;&ccedil;k&uuml;nlərə və məskunlaşmamış qa&ccedil;qınlara &ouml;dənişlər&rdquo; və &ldquo;272900. Sosial yardım &uuml;zrə digər &ouml;dənişlər&rdquo; paraqraflarından ibarətdir.</p>'),
(37, 38, 'Digər sosial ödənişlər', 279000, '1', '<p><strong>279000. &ldquo;Digər sosial &ouml;dənişlər&rdquo;&nbsp;</strong>k&ouml;mək&ccedil;i b&ouml;lməsinə m&ouml;vcud qanunvericiliyə uyğun olaraq d&ouml;vlət qulluq&ccedil;ularına &ouml;dənilən sosial m&uuml;avinətlər və 271000-272000-ci k&ouml;mək&ccedil;i b&ouml;lmələrində &ouml;z əksini tapmayan &ouml;dənişlər &uuml;zrə xərclər daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;279100. D&ouml;vlət qulluq&ccedil;ularına &ouml;dənişlər&rdquo;, &ldquo;279200. Natural formada olan m&uuml;avinətlər&rdquo;, &ldquo;279300. Kommunal və digər xidmətlərə g&ouml;rə təzminat (kompensasiya)&rdquo; və &ldquo;279900. Digər m&uuml;avinətlər&rdquo; paraqraflarından ibarətdir.</p>'),
(38, 39, 'Torpaq, tikili və avadanlıqlar', 311000, '1', '<p><strong>311000. &ldquo;Torpaq, tikili və avadanlıqlar&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə tikili və avadanlıqların, nəqliyyat vasitələrinin, sair torpaq, tikili və avadanlıqların alınması və tikilməsi ilə bağlı xərclər daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;311100. Tikili və avadanlıqlar&rdquo;, &ldquo;311200. Nəqliyyat vasitələri&rdquo; və &ldquo;311900. Sair torpaq, tikili və avadanlıqlar&rdquo; paraqraflarından ibarətdir.</p>'),
(39, 39, 'Əsaslı təmir', 312000, '1', '<p><strong>312000. &ldquo;Əsaslı təmir&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə yararsız vəziyyətə d&uuml;şm&uuml;ş və yararsız vəziyyətə d&uuml;şmək ərəfəsində olan sosial və infrastruktur obyektlərin, nəqliyyat vasitələrinin, maşın və avadanlıqların, qurğu və &ouml;t&uuml;r&uuml;c&uuml; qurğuların və bu qəbildən olan digər əmlakların tam bərpası, yenidən qurulması &uuml;&ccedil;&uuml;n sərf olunan xərclər daxildir. Həm&ccedil;inin, bu maddəyə əsas vəsaitlərin (fondların) əsaslı təmiri və əsaslı təmir işləri ilə bağlı layihə-smeta sənədlərinin hazırlanması xərcləri daxil edilir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;312100. Tikili və avadanlıqların əsaslı təmiri&rdquo;, &ldquo;312200. Nəqliyyat vasitələrinin əsaslı təmiri&rdquo; və &ldquo;312900. Sair torpaq, tikili və avadanlıqların əsaslı təmiri&rdquo; paraqraflarından ibarətdir.</p>'),
(40, 39, 'Əsaslı vəsait qoyuluşu (investisiya) xərci', 313000, '1', '<p><strong>313000. &ldquo;Əsaslı vəsait qoyuluşu (investisiya) xərci&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə hər il &uuml;zrə d&ouml;vlət b&uuml;dcəsində d&ouml;vlət əsaslı vəsait qoyuluşu (investisiya) xərci &uuml;&ccedil;&uuml;n nəzərdə tutulan vəsait daxildir.</p>'),
(41, 39, 'Qeyri-maddi aktivlər', 314000, '1', '<p><strong>314000. &ldquo;Qeyri-maddi aktivlər&rdquo;&nbsp;</strong>k&ouml;mək&ccedil;i b&ouml;lməsində torpaq sahələrindən, təbii ehtiyatlardan (sərvətlərdən) istifadə &uuml;&ccedil;&uuml;n verilmiş uzunm&uuml;ddətli h&uuml;quqların, patentlərin, lisenziyaların, ticarət markalarının, əmtəə nişanlarının alınması, proqram təminatlarının, komp&uuml;ter proqramlarının, idarə əməkdaşlarına verilən elektron imza sertifikatlarının və digər qeyri-maddi aktivlərin alınması, quraşdırılması, sazlanması, habelə qeyri-maddi aktivlərin yaradılması və ya onların balans dəyərinin artırılması &uuml;zrə xərclər daxildir.</p>'),
(42, 39, 'Bioloji aktivlər', 315000, '1', '<p><strong>315000. &ldquo;Bioloji aktivlər&rdquo;&nbsp;</strong>k&ouml;mək&ccedil;i b&ouml;lməsinə iş&ccedil;i və məhsuldar heyvanların, &ccedil;oxillik əkmələrin və sair bioloji aktivlərin alınması və yetişdirilməsi ilə bağlı xərclər daxildir.</p>'),
(43, 39, 'Sair uzunmüddətli qeyri-maliyyə aktivləri', 316000, '1', '<p><strong>316000. &ldquo;Sair uzunm&uuml;ddətli qeyri-maliyyə aktivləri&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə kitabxana fondu (elektron və kağız daşıyıcılarda b&uuml;t&uuml;n n&ouml;v elmi, bədii, tədris və x&uuml;susi n&ouml;v ədəbiyyatlar və bu kimi digər nəşrlər), muzey sərvətləri, qalereyalar &uuml;&ccedil;&uuml;n eksponatlar və rəsm əsərləri, məlumat daşıyıcıları (tədris kinofilmləri, maqnit lentləri, maqnit diskləri, kasetlər, proqram daşıyıcıları və bu kimi başqa məlumat daşıyıcıları), heyvanxanalarda olan d&uuml;nya heyvanlarının eksponatları və bu kimi digər uzunm&uuml;ddətli qeyri-maliyyə aktivlərinin alınması, quraşdırılması və istehsalı, habelə b&uuml;st və heykəllərin layihələndirilməsi və hazırlanması ilə bağlı xərclər daxildir.</p>'),
(44, 39, 'Maddi-istehsal ehtiyatları', 317000, '1', '<p><strong>317000. &ldquo;Maddi-istehsal ehtiyatları&rdquo;&nbsp;</strong>k&ouml;mək&ccedil;i b&ouml;lməsinə satış &uuml;&ccedil;&uuml;n nəzərdə tutulan mallar, d&ouml;vlət orqanları tərəfindən f&ouml;vqəladə, səfərbərlik və strateji mal ehtiyatlarının, o c&uuml;mlədən taxıl ehtiyatlarının və &ouml;lkə &uuml;&ccedil;&uuml;n vacib olan digər malların, habelə d&ouml;vlət material ehtiyatları yaradılması məqsədi ilə m&uuml;xtəlif ehtiyatların və qiymətli metalların və daşların, habelə zərgərlik məmulatlarının alınması və yaradılması xərcləri daxildir.</p>'),
(45, 39, 'Qeyri-istehsal aktivləri', 318000, '1', '<p><strong>318000. &ldquo;Qeyri-istehsal aktivləri&rdquo;&nbsp;</strong>k&ouml;mək&ccedil;i b&ouml;lməsinə torpağın (onlarda yerləşən tikinti obyektləri və qurğulardan başqa), meşənin, yeraltı sərvətlərin və faydalı qazıntıların yerinin alınması ilə bağlı xərclər daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;318100. Torpaq&rdquo; və &ldquo;318200. Yeraltı aktivlər və digər təbii aktivlər&rdquo; paraqraflarından ibarətdir.</p>'),
(46, 40, 'Daxili', 321000, '1', '<p><strong>321000. &ldquo;Daxili&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə &ouml;lkə daxilində d&ouml;vlətə məxsus cari və tranzit hesablar, depozitlər, istiqrazlar, qiymətli kağızlar, daxili borclar &uuml;zrə əməliyyatlar daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;321100. Valyuta və depozitlər&rdquo;, &ldquo;321200. Səhmlər istisna olmaqla qiymətli kağızlar&rdquo;, &ldquo;321300. Ssudalar&rdquo;, &ldquo;321400. Səhm və digər kapital&rdquo;, &ldquo;321500. T&ouml;rəmə maliyyə alətləri&rdquo; və &ldquo;321900. Digər maliyyə aktivləri&rdquo; paraqraflarından ibarətdir.</p>'),
(47, 40, 'Xarici', 322000, '1', '<p>322000. &ldquo;Xarici&rdquo;&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə &ouml;lkə xaricində d&ouml;vlətə məxsus cari və tranzit hesablar, qiymətli kağızlar (səhmlər istisna olmaqla), ssudalar, xarici borclar &uuml;zrə əməliyyatlar daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;322100. Valyuta və depozitlər&rdquo;, &ldquo;322200. Səhmlər istisna olmaqla qiymətli kağızlar&rdquo;, &ldquo;322300. Ssudalar&rdquo;, &ldquo;322400. Səhm və digər kapital&rdquo;, &ldquo;322500. T&ouml;rəmə maliyyə alətləri&rdquo; və &ldquo;322900. Digər maliyyə aktivləri&rdquo; paraqraflarından ibarətdir.</p>'),
(48, 40, 'Qızıl və SDR', 323000, '1', '<p><strong>323000.&nbsp;&ldquo;Qızıl və SDR&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə&nbsp;qızıl və SDR (Beynəlxalq Valyuta Fondunun x&uuml;susi borclanma vahidi) maliyyə aktivlərinin yaradılması &uuml;zrə əməliyyatlar daxildir.</p>'),
(49, 41, 'Daxili', 331000, '1', '<p><strong>331000. &ldquo;Daxili&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə d&ouml;vlətin &uuml;zərinə d&uuml;şən və &ouml;hdəlik yaradan depozit və valyuta hesabları &uuml;zrə əməliyyatlar, d&ouml;vlətin qiymətli kağızlarının və istiqrazlarının satışından yaranan &ouml;hdəliklər və daxili borclanmadan yaranan &ouml;hdəliklər &uuml;zrə əməliyyatlar daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;331100. Valyuta və depozitlər&rdquo;, &ldquo;331200. Səhmlər istisna olmaqla qiymətli kağızlar&rdquo;, &ldquo;331300. Ssudalar&rdquo;, &ldquo;331400. Səhm və digər kapital&rdquo; və &ldquo;331500. Digər maliyyə &ouml;hdəlikləri&rdquo; paraqraflarından ibarətdir.</p>'),
(50, 41, 'Xarici', 332000, '1', '<p><strong>332000. &ldquo;Xarici&rdquo;</strong>&nbsp;k&ouml;mək&ccedil;i b&ouml;lməsinə d&ouml;vlətin &uuml;zərinə d&uuml;şən və &ouml;hdəlik yaradan depozit və valyuta hesabları &uuml;zrə əməliyyatlar, qiymətli kağızların və istiqrazların satışından yaranan &ouml;hdəliklər və xarici borclanmadan yaranan &ouml;hdəliklər &uuml;zrə əməliyyatlar daxildir. Bu k&ouml;mək&ccedil;i b&ouml;lmə &ldquo;332100. Valyuta və depozitlər&rdquo;, &ldquo;332200. Səhmlər istisna olmaqla qiymətli kağızlar&rdquo;, &ldquo;332300. Ssudalar&rdquo;, &ldquo;332400. Səhm və digər kapital&rdquo; və &ldquo;332500. Digər maliyyə &ouml;hdəlikləri&rdquo; paraqraflarından ibarətdir.</p>');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `iqtisaditesnifat_kb`
--
ALTER TABLE `iqtisaditesnifat_kb`
  ADD PRIMARY KEY (`iqtisaditesnifat_kb_id`),
  ADD UNIQUE KEY `iqtisaditesnifat_kb_id` (`iqtisaditesnifat_kb_id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `iqtisaditesnifat_kb`
--
ALTER TABLE `iqtisaditesnifat_kb`
  MODIFY `iqtisaditesnifat_kb_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
